package com.techjs.thephotoalbum.utils;

public enum SQLQueriesConstants {
	CREATE_USER_TABLE,
	CREATE_ALBUM_TABLE,
	CREATE_PHOTO_TABLE,
	DROP_MOBILE_UPLOAD_ALBUM_TRIGGER,
	CREATE_MOBILE_UPLOAD_ALBUM_TRIGGER
}
